%YAML 1.3
---
- MouseGesture: Mouse Up
- Execute: [hyprctl, dispatch, workspace, special]
...
---
- MouseGesture: Mouse Left
- Execute: [hyprctl, dispatch, workspace, e-1]
...
---
- MouseGesture: Mouse Down
- Execute: [hyprctl, dispatch, togglespecialworkspace]
...
---
- MouseGesture: Mouse Right
- Execute: [hyprctl, dispatch, workspace, e+1]
...
